param(
   [string]$ResultsPath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_MODEL1_RESULTS.csv',
   [string]$ManifestPath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_MODEL1_MANIFEST.csv',
   [string]$RunPath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_RUN_ATTESTATION.csv',
   [string]$CompilePath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_COMPILE_AUDIT.csv',
   [string]$DecisionCsvPath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_DECISION.csv',
   [string]$DecisionMarkdownPath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_DECISION.md'
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$expectedSource='5D756F58DDAB31D2DC909B8DD800C8D888582691A7208FFD7FD1E3F597D3A5C6';$expectedBinary='9BC3BAEC7D5BA0945E6974C960AC900D6F019C5A174D217712FF8B7E8137C32A'
function Resolve-RepoPath([string]$Path){if([IO.Path]::IsPathRooted($Path)){return $Path};return Join-Path $repo $Path}
function Money([double]$Value){if($Value-ge0){return ('+${0:N2}'-f$Value)};return ('-${0:N2}'-f[math]::Abs($Value))}
$results=@(Import-Csv (Resolve-RepoPath $ResultsPath));$manifest=@(Import-Csv (Resolve-RepoPath $ManifestPath));$runs=@(Import-Csv (Resolve-RepoPath $RunPath));$compile=@(Import-Csv (Resolve-RepoPath $CompilePath))
if($results.Count-ne15-or$manifest.Count-ne15-or$runs.Count-ne15){throw 'Expected 15 results, manifest rows, and canonical runs.'};if(@($results|Where-Object Status -ne PARSED).Count-or@($runs|Where-Object Status -ne REPORT_FOUND).Count){throw 'Evidence is incomplete.'};if(@($results|Where-Object{$_.To-gt'2020.12.31'}).Count){throw 'Post-2020 data leaked into discovery.'}
if($compile.Count-ne1-or$compile[0].Status-ne'COMPILE_PASS'-or$compile[0].SourceSha256-ne$expectedSource-or$compile[0].PortableBinarySha256-ne$expectedBinary-or[int]$compile[0].CompileErrors-ne0-or[int]$compile[0].CompileWarnings-ne0){throw 'Compile identity mismatch.'}
foreach($row in $results){$m=@($manifest|Where-Object QueueRank -eq $row.QueueRank);$run=@($runs|Where-Object QueueRank -eq $row.QueueRank);if($m.Count-ne1-or$run.Count-ne1-or$row.ProfileSha256-ne$m[0].ProfileSha256-or$row.SourceSha256-ne$expectedSource-or$run[0].PackageSourceSha256-ne$expectedSource-or$run[0].PortableBinarySha256-ne$expectedBinary){throw "Identity mismatch at rank $($row.QueueRank)."}}
$base=@();foreach($group in ($results|Group-Object Candidate)){$older=@($group.Group|Where-Object Window -eq older_2015_2018);$recent=@($group.Group|Where-Object Window -eq discovery_2019_2020);$continuous=@($group.Group|Where-Object Window -eq continuous_2015_2020);if($group.Count-ne3-or$older.Count-ne1-or$recent.Count-ne1-or$continuous.Count-ne1){throw "Window mismatch for $($group.Name)."};$x=$continuous[0];$base+=[pscustomobject]@{Candidate=$group.Name;Role=$x.Role;Enabled=[bool]::Parse($x.FeatureEnabled);Positions=[int]$x.MaximumAccountPositions;Risk=[double]$x.SqueezeRiskPercent;Older=[double]$older[0].NetProfit;Recent=[double]$recent[0].NetProfit;Net=[double]$x.NetProfit;Cagr=[double]$x.CagrPercent;PF=[double]$x.ProfitFactor;Trades=[int]$x.TotalTrades;DD=[double]$x.MaxDrawdownPercent;Recovery=[double]$x.RecoveryFactor;ReturnDD=if([double]$x.MaxDrawdownPercent-gt0){[double]$x.TotalReturnPercent/[double]$x.MaxDrawdownPercent}else{0}}}
$control=@($base|Where-Object Candidate -eq sq_exact_control);$capacity=@($base|Where-Object Candidate -eq sq_capacity_control);if($control.Count-ne1-or$capacity.Count-ne1){throw 'Both disabled controls are required.'};$control=$control[0];$capacity=$capacity[0]
$capacityExact=$capacity.Older-eq$control.Older-and$capacity.Recent-eq$control.Recent-and$capacity.Net-eq$control.Net-and$capacity.Cagr-eq$control.Cagr-and$capacity.PF-eq$control.PF-and$capacity.Trades-eq$control.Trades-and$capacity.DD-eq$control.DD-and$capacity.Recovery-eq$control.Recovery
$rows=foreach($row in $base){$olderGrowth=$row.Older/$control.Older-1;$recentGrowth=$row.Recent/$control.Recent-1;$netGrowth=$row.Net/$control.Net-1;$cagrGrowth=$row.Cagr-$control.Cagr;$positive=$row.Older-gt0-and$row.Recent-gt0-and$row.Net-gt0;$added=$row.Trades-$control.Trades;$drawdown=$row.DD-le1.30-and$row.DD-le$control.DD+.10;$efficiency=$row.PF-ge.98*$control.PF-and$row.Recovery-ge.98*$control.Recovery-and$row.ReturnDD-ge.98*$control.ReturnDD;$changed=[math]::Abs($row.Net-$control.Net)-gt.01;$centerGate=$capacityExact-and$row.Candidate-eq'sq_center0100'-and$row.Enabled-and$positive-and$netGrowth-ge.08-and$cagrGrowth-ge.12-and$added-ge40-and$efficiency-and$drawdown-and$changed;$supportGate=$capacityExact-and$row.Candidate-in@('sq_low0075','sq_high0125')-and$row.Enabled-and$positive-and$netGrowth-ge.04-and$cagrGrowth-ge.06-and$added-ge30-and$efficiency-and$drawdown-and$changed;[pscustomobject]@{Candidate=$row.Candidate;Role=$row.Role;FeatureEnabled=$row.Enabled;MaximumAccountPositions=$row.Positions;SqueezeRiskPercent=$row.Risk;OlderNet=[math]::Round($row.Older,2);OlderGrowthPercent=[math]::Round(100*$olderGrowth,2);RecentNet=[math]::Round($row.Recent,2);RecentGrowthPercent=[math]::Round(100*$recentGrowth,2);ContinuousNet=[math]::Round($row.Net,2);NetGrowthPercent=[math]::Round(100*$netGrowth,2);CagrPercent=[math]::Round($row.Cagr,2);CagrGrowthPoints=[math]::Round($cagrGrowth,2);ProfitFactor=[math]::Round($row.PF,2);ProfitFactorRetentionPercent=[math]::Round(100*$row.PF/$control.PF,2);Trades=$row.Trades;AddedTrades=$added;MaxDrawdownPercent=[math]::Round($row.DD,2);RecoveryFactor=[math]::Round($row.Recovery,4);ReturnDrawdownRatio=[math]::Round($row.ReturnDD,4);PositiveAllWindows=$positive;CapacityControlExact=$capacityExact;EfficiencyPass=$efficiency;DrawdownPass=$drawdown;CenterGatePass=$centerGate;NeighborSupportPass=$supportGate}}
$center=@($rows|Where-Object Candidate -eq sq_center0100);$support=@($rows|Where-Object NeighborSupportPass).Count;$open=$center.Count-eq1-and$center[0].CenterGatePass-and$support-ge1
$decisionRows=$rows|Sort-Object SqueezeRiskPercent,FeatureEnabled|ForEach-Object{$_|Add-Member -NotePropertyName Decision -NotePropertyValue $(if($open-and$_.Candidate-eq'sq_center0100'){'OPEN_FROZEN_POST2020_GATE'}else{'REJECTED_OR_CONTROL'}) -PassThru};$decisionRows|Export-Csv (Resolve-RepoPath $DecisionCsvPath) -NoTypeInformation -Encoding ASCII
$md=[Collections.Generic.List[string]]::new();$md.Add('# Four-Lane M15 Squeeze Diversifier Discovery Decision');$md.Add('');$md.Add($(if($open){'**Decision: pre-2021 discovery passed. Open only the exact 0.10% center in a separately frozen post-2020 gate.**'}else{'**Decision: rejected in frozen pre-2021 discovery. No post-2020 test, Model 4 run, promotion, forward change, or live approval was opened.**'}));$md.Add('');$md.Add("- Research source SHA-256: ``$expectedSource``");$md.Add("- Four-worker EX5 SHA-256: ``$expectedBinary``");$md.Add('- Reports: `15 / 15` parsed and identity-valid after one unchanged export recovery.');$md.Add('- Data: 2015-2020 Model 1 only; newer data remained unopened for this exact integration.');$md.Add("- Disabled four-position capacity control exactly reproduced the leader control: ``$capacityExact``.");$md.Add('');$md.Add('| Candidate | SQ risk | 2015-18 | 2019-20 | Continuous | Change | CAGR | PF | PF retained | Trades | DD | Recovery | Gate |');$md.Add('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|');foreach($row in $decisionRows){$gate=$row.CenterGatePass-or$row.NeighborSupportPass;$md.Add("| ``$($row.Candidate)`` | ``$('{0:N3}'-f$row.SqueezeRiskPercent)%`` | ``$(Money $row.OlderNet)`` | ``$(Money $row.RecentNet)`` | ``$(Money $row.ContinuousNet)`` | ``$('{0:N2}'-f$row.NetGrowthPercent)%`` | ``$('{0:N2}'-f$row.CagrPercent)%`` | ``$('{0:N2}'-f$row.ProfitFactor)`` | ``$('{0:N2}'-f$row.ProfitFactorRetentionPercent)%`` | ``$($row.Trades)`` | ``$('{0:N2}'-f$row.MaxDrawdownPercent)%`` | ``$('{0:N2}'-f$row.RecoveryFactor)`` | ``$(if($gate){'pass'}else{'fail/control'})`` |")};$md.Add('');$md.Add($(if($open){"The fixed center passed with $support preregistered adjacent support row(s). This only opens a separate post-2020 validation; it is not a promotion."}else{'Dollar profit, CAGR, activity, drawdown, recovery, and return/drawdown improved, but every enabled row failed the frozen 98% profit-factor retention requirement. The center is not rescued by weakening that gate after observation.'}));$md.Add('');$md.Add('- The published leader, frozen forward candidate, invalid $100,000 demo registration, and real-account lock remain unchanged.');$md|Set-Content (Resolve-RepoPath $DecisionMarkdownPath) -Encoding ASCII
[pscustomobject]@{Status=if($open){'OPEN_FROZEN_POST2020_GATE'}else{'REJECTED'};Reports=15;Candidates=5;CapacityControlExact=$capacityExact;CenterPass=$center[0].CenterGatePass;AdjacentPasses=$support;Post2020Opened=$open;Model4Runs=0;NewBest=$false}
