param(
   [string]$ResultsPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_MODEL1_RESULTS.csv',
   [string]$ManifestPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_MODEL1_MANIFEST.csv',
   [string]$RunPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_RUN_ATTESTATION.csv',
   [string]$CompilePath='outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_COMPILE_AUDIT.csv',
   [string]$DecisionCsvPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_DECISION.csv',
   [string]$DecisionMarkdownPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_DECISION.md'
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$expectedSource='5D756F58DDAB31D2DC909B8DD800C8D888582691A7208FFD7FD1E3F597D3A5C6';$expectedBinary='9BC3BAEC7D5BA0945E6974C960AC900D6F019C5A174D217712FF8B7E8137C32A'
function Resolve-RepoPath([string]$Path){if([IO.Path]::IsPathRooted($Path)){return $Path};return Join-Path $repo $Path};function Money([double]$Value){if($Value-ge0){return ('+${0:N2}'-f$Value)};return ('-${0:N2}'-f[math]::Abs($Value))}
$results=@(Import-Csv (Resolve-RepoPath $ResultsPath));$manifest=@(Import-Csv (Resolve-RepoPath $ManifestPath));$runs=@(Import-Csv (Resolve-RepoPath $RunPath));$compile=@(Import-Csv (Resolve-RepoPath $CompilePath));if($results.Count-ne18-or$manifest.Count-ne18-or$runs.Count-ne18){throw 'Expected 18 results, manifest rows, and canonical runs.'};if(@($results|Where-Object Status -ne PARSED).Count-or@($runs|Where-Object Status -ne REPORT_FOUND).Count){throw 'Evidence is incomplete.'};if(@($results|Where-Object{$_.To-gt'2020.12.31'}).Count){throw 'Post-2020 data leaked into discovery.'}
if($compile.Count-ne1-or$compile[0].Status-ne'COMPILE_PASS'-or$compile[0].SourceSha256-ne$expectedSource-or$compile[0].PortableBinarySha256-ne$expectedBinary-or[int]$compile[0].CompileErrors-ne0-or[int]$compile[0].CompileWarnings-ne0){throw 'Compile identity mismatch.'};foreach($row in $results){$m=@($manifest|Where-Object QueueRank -eq $row.QueueRank);$run=@($runs|Where-Object QueueRank -eq $row.QueueRank);if($m.Count-ne1-or$run.Count-ne1-or$row.ProfileSha256-ne$m[0].ProfileSha256-or$row.SourceSha256-ne$expectedSource-or$run[0].PackageSourceSha256-ne$expectedSource-or$run[0].PortableBinarySha256-ne$expectedBinary){throw "Identity mismatch at rank $($row.QueueRank)."}}
$base=@();foreach($group in ($results|Group-Object Candidate)){$older=@($group.Group|Where-Object Window -eq older_2015_2018);$recent=@($group.Group|Where-Object Window -eq discovery_2019_2020);$continuous=@($group.Group|Where-Object Window -eq continuous_2015_2020);if($group.Count-ne3-or$older.Count-ne1-or$recent.Count-ne1-or$continuous.Count-ne1){throw "Window mismatch for $($group.Name)."};$x=$continuous[0];$base+=[pscustomobject]@{Candidate=$group.Name;Role=$x.Role;Enabled=[bool]::Parse($x.FeatureEnabled);Target=[double]$x.SqueezeTakeProfitR;Older=[double]$older[0].NetProfit;Recent=[double]$recent[0].NetProfit;Net=[double]$x.NetProfit;Cagr=[double]$x.CagrPercent;PF=[double]$x.ProfitFactor;Trades=[int]$x.TotalTrades;DD=[double]$x.MaxDrawdownPercent;Recovery=[double]$x.RecoveryFactor;ReturnDD=if([double]$x.MaxDrawdownPercent-gt0){[double]$x.TotalReturnPercent/[double]$x.MaxDrawdownPercent}else{0}}}
$control=@($base|Where-Object Candidate -eq sqt_exact_control);$capacity=@($base|Where-Object Candidate -eq sqt_capacity_control);$reference=@($base|Where-Object Candidate -eq sqt_reference150);if($control.Count-ne1-or$capacity.Count-ne1-or$reference.Count-ne1){throw 'Required controls/reference are missing.'};$control=$control[0];$capacity=$capacity[0];$reference=$reference[0]
function Same-Metrics($a,$b){return $a.Older-eq$b.Older-and$a.Recent-eq$b.Recent-and$a.Net-eq$b.Net-and$a.Cagr-eq$b.Cagr-and$a.PF-eq$b.PF-and$a.Trades-eq$b.Trades-and$a.DD-eq$b.DD-and$a.Recovery-eq$b.Recovery}
$capacityExact=Same-Metrics $capacity $control;$referenceExact=$reference.Older-eq1141.49-and$reference.Recent-eq459.89-and$reference.Net-eq1575.70-and$reference.Cagr-eq2.47-and$reference.PF-eq1.78-and$reference.Trades-eq350-and$reference.DD-eq1.10-and$reference.Recovery-eq13.4434
$rows=foreach($row in $base){$netGrowth=$row.Net/$control.Net-1;$cagrGrowth=$row.Cagr-$control.Cagr;$positive=$row.Older-gt0-and$row.Recent-gt0-and$row.Net-gt0;$erasNoWorse=$row.Older-ge$control.Older-and$row.Recent-ge$control.Recent;$drawdown=$row.DD-le1.30-and$row.DD-le$control.DD+.15;$centerEfficiency=$row.PF-ge.98*$control.PF-and$row.Recovery-ge$control.Recovery-and$row.ReturnDD-ge$control.ReturnDD;$supportEfficiency=$row.PF-ge.98*$control.PF-and$row.Recovery-ge.98*$control.Recovery-and$row.ReturnDD-ge.98*$control.ReturnDD;$changed=[math]::Abs($row.Net-$reference.Net)-gt.01;$centerGate=$capacityExact-and$referenceExact-and$row.Candidate-eq'sqt_center200'-and$row.Enabled-and$positive-and$erasNoWorse-and$netGrowth-ge.10-and$cagrGrowth-ge.20-and$centerEfficiency-and$drawdown-and$row.Trades-ge300-and$changed;$supportGate=$capacityExact-and$referenceExact-and$row.Candidate-in@('sqt_low175','sqt_high225')-and$row.Enabled-and$positive-and$erasNoWorse-and$netGrowth-ge.08-and$cagrGrowth-ge.15-and$supportEfficiency-and$drawdown-and$row.Trades-ge300-and$changed;[pscustomobject]@{Candidate=$row.Candidate;Role=$row.Role;FeatureEnabled=$row.Enabled;SqueezeTakeProfitR=$row.Target;OlderNet=[math]::Round($row.Older,2);RecentNet=[math]::Round($row.Recent,2);ContinuousNet=[math]::Round($row.Net,2);NetGrowthPercent=[math]::Round(100*$netGrowth,2);CagrPercent=[math]::Round($row.Cagr,2);CagrGrowthPoints=[math]::Round($cagrGrowth,2);ProfitFactor=[math]::Round($row.PF,2);ProfitFactorRetentionPercent=[math]::Round(100*$row.PF/$control.PF,2);Trades=$row.Trades;MaxDrawdownPercent=[math]::Round($row.DD,2);RecoveryFactor=[math]::Round($row.Recovery,4);ReturnDrawdownRatio=[math]::Round($row.ReturnDD,4);PositiveAllWindows=$positive;ErasNoWorse=$erasNoWorse;CapacityControlExact=$capacityExact;ReferenceExact=$referenceExact;DrawdownPass=$drawdown;CenterGatePass=$centerGate;NeighborSupportPass=$supportGate}}
$center=@($rows|Where-Object Candidate -eq sqt_center200);$support=@($rows|Where-Object NeighborSupportPass).Count;$open=$center.Count-eq1-and$center[0].CenterGatePass-and$support-ge1;$decisionRows=$rows|Sort-Object SqueezeTakeProfitR,FeatureEnabled|ForEach-Object{$_|Add-Member -NotePropertyName Decision -NotePropertyValue $(if($open-and$_.Candidate-eq'sqt_center200'){'OPEN_FROZEN_POST2020_GATE'}else{'REJECTED_OR_CONTROL'}) -PassThru};$decisionRows|Export-Csv (Resolve-RepoPath $DecisionCsvPath) -NoTypeInformation -Encoding ASCII
$md=[Collections.Generic.List[string]]::new();$md.Add('# Four-Lane M15 Squeeze Target Interaction Decision');$md.Add('');$md.Add($(if($open){'**Decision: pre-2021 interaction passed. Open only the exact 2.00R center in a separately frozen post-2020 gate.**'}else{'**Decision: rejected in frozen pre-2021 discovery. No post-2020 test, Model 4 run, promotion, forward change, or live approval was opened.**'}));$md.Add('');$md.Add("- Research source SHA-256: ``$expectedSource``");$md.Add("- Reused four-worker EX5 SHA-256: ``$expectedBinary``");$md.Add('- Reports: `18 / 18` parsed and identity-valid after three unchanged export recoveries.');$md.Add('- Data: 2015-2020 Model 1 only; newer data remained unopened for this exact interaction.');$md.Add("- Disabled capacity control exact: ``$capacityExact``; enabled 1.50R reference exact: ``$referenceExact``.");$md.Add('');$md.Add('| Candidate | Target | 2015-18 | 2019-20 | Continuous | Change | CAGR | PF | PF retained | Trades | DD | Recovery | Gate |');$md.Add('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|');foreach($row in $decisionRows){$gate=$row.CenterGatePass-or$row.NeighborSupportPass;$md.Add("| ``$($row.Candidate)`` | ``$('{0:N2}'-f$row.SqueezeTakeProfitR)R`` | ``$(Money $row.OlderNet)`` | ``$(Money $row.RecentNet)`` | ``$(Money $row.ContinuousNet)`` | ``$('{0:N2}'-f$row.NetGrowthPercent)%`` | ``$('{0:N2}'-f$row.CagrPercent)%`` | ``$('{0:N2}'-f$row.ProfitFactor)`` | ``$('{0:N2}'-f$row.ProfitFactorRetentionPercent)%`` | ``$($row.Trades)`` | ``$('{0:N2}'-f$row.MaxDrawdownPercent)%`` | ``$('{0:N2}'-f$row.RecoveryFactor)`` | ``$(if($gate){'pass'}else{'fail/control'})`` |")};$md.Add('');$md.Add($(if($open){"The fixed center passed with $support adjacent support row(s). This only opens a separate post-2020 validation; it is not a promotion."}else{'The 2.25R upper edge met the numeric neighbor gate and had the highest headline result, but the preregistered 2.00R center retained only 96.81% of control PF versus the required 98%. Selecting the observed upper edge or moving the center after observation is forbidden.'}));$md.Add('');$md.Add('- The published leader, frozen forward candidate, invalid $100,000 demo registration, and real-account lock remain unchanged.');$md|Set-Content (Resolve-RepoPath $DecisionMarkdownPath) -Encoding ASCII
[pscustomobject]@{Status=if($open){'OPEN_FROZEN_POST2020_GATE'}else{'REJECTED'};Reports=18;Candidates=6;CapacityControlExact=$capacityExact;ReferenceExact=$referenceExact;CenterPass=$center[0].CenterGatePass;AdjacentPasses=$support;Post2020Opened=$open;Model4Runs=0;NewBest=$false}
