[CmdletBinding()]
param(
   [string]$SourcePath='work\Professional_XAUUSD_Four_Lane_M15_Squeeze_Diversifier_Research.mq5',
   [string]$LeaderProfilePath='release\three-lane-momentum-same-side-exit-cooldown-provisional\THREE_LANE_MOMENTUM_SAME_SIDE_EXIT_COOLDOWN_PROVISIONAL.set',
   [string]$PackageDir='outputs\four_lane_m15_squeeze_target_interaction_discovery_model1_package',
   [string]$ManifestPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_MODEL1_MANIFEST.csv',
   [string]$ContractPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_CONTRACT.md'
)

$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'seasonal_gate_helpers.ps1')
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$outputsRoot=(Resolve-Path (Join-Path $repo 'outputs')).Path
$expectedSourceHash='5D756F58DDAB31D2DC909B8DD800C8D888582691A7208FFD7FD1E3F597D3A5C6';$expectedLeaderHash='ACFCE73E2A48723334CC416715F047E3CEA87018D46B12B8A6CB0663E025BA1C'
$expectedIntegrationDecisionHash='8263EE47CA4BD74160BBE93B28BCF695DF641C9E60AF296C7B7FD6CEDD8A03DF';$expectedLedgerHash='402216282F464C9E1BA5DFC4A81DBF94CAD44D56C74985D852FE6D634B0C84CC';$expectedIndependentDecisionHash='FA92B99DE4AF5F6F8E2357CECD89893E50DD0156B696D5714DEAAE3EBDD8E821'
function Resolve-RepoPath([string]$Path){if([IO.Path]::IsPathRooted($Path)){return $Path};return Join-Path $repo $Path}
function Convert-SourceDefault([string]$Type,[string]$Value){$v=$Value.Trim();if($Type-eq'string'){return $v.Substring(1,$v.Length-2)};if($Type-eq'ENUM_TIMEFRAMES'){$map=@{PERIOD_M15='15';PERIOD_H1='16385';PERIOD_H4='16388';PERIOD_D1='16408'};if(!$map.ContainsKey($v)){throw "Unsupported timeframe: $v"};return $map[$v]};return $v}
function Get-SourceInputs([string]$Path){$inputs=[ordered]@{};foreach($line in Get-Content -LiteralPath $Path){if($line-notmatch'^\s*input\s+([A-Za-z_][A-Za-z0-9_]*)\s+(Inp[A-Za-z0-9_]+)\s*=\s*(.+?)\s*;\s*$'){continue};$type=$Matches[1];$name=$Matches[2];$value=Convert-SourceDefault $type $Matches[3];if($inputs.Contains($name)){throw "Duplicate input: $name"};$inputs[$name]=if($type-eq'string'){"$name=$value"}else{"$name=$value||$value||0||0||N"}};return $inputs}
function Copy-Inputs($Inputs){$copy=[ordered]@{};foreach($key in $Inputs.Keys){$copy[$key]=$Inputs[$key]};return $copy}
function Set-FixedInput($Inputs,[string]$Name,[string]$Value,[switch]$StringValue){if(!$Inputs.Contains($Name)){throw "Unknown input: $Name"};$Inputs[$Name]=if($StringValue){"$Name=$Value"}else{"$Name=$Value||$Value||0||0||N"}}
function Assert-Hash([string]$Path,[string]$Expected,[string]$Label){$actual=(Get-FileHash -LiteralPath (Resolve-RepoPath $Path) -Algorithm SHA256).Hash.ToUpperInvariant();if($actual-ne$Expected){throw "$Label changed: $actual"}}
function Clear-OutputDirSafe([string]$Path){if(Test-Path -LiteralPath $Path){$resolved=(Resolve-Path -LiteralPath $Path).Path;if(!$resolved.StartsWith($outputsRoot,[StringComparison]::OrdinalIgnoreCase)){throw "Refusing to clear $resolved"};Remove-Item -LiteralPath $resolved -Recurse -Force};New-Item -ItemType Directory -Path $Path -Force|Out-Null}

& (Join-Path $PSScriptRoot 'test_four_lane_m15_squeeze_diversifier_source.ps1')|Out-Null
Assert-Hash 'outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_DECISION.md' $expectedIntegrationDecisionHash 'Integration decision'
Assert-Hash 'outputs\FOUR_LANE_M15_SQUEEZE_DIVERSIFIER_DISCOVERY_TRADES.csv' $expectedLedgerHash 'Integration ledger'
Assert-Hash 'outputs\INDEPENDENT_M15_VOLATILITY_SQUEEZE_DISCOVERY_DECISION.md' $expectedIndependentDecisionHash 'Independent squeeze decision'
$source=(Resolve-Path -LiteralPath (Resolve-RepoPath $SourcePath)).Path;$leader=(Resolve-Path -LiteralPath (Resolve-RepoPath $LeaderProfilePath)).Path
$sourceHash=(Get-FileHash $source -Algorithm SHA256).Hash.ToUpperInvariant();$leaderHash=(Get-FileHash $leader -Algorithm SHA256).Hash.ToUpperInvariant();if($sourceHash-ne$expectedSourceHash){throw 'Research source changed.'};if($leaderHash-ne$expectedLeaderHash){throw 'Leader profile changed.'}
$base=Get-SourceInputs $source;if($base.Count-ne247){throw "Expected 247 source inputs, found $($base.Count)."};$leaderCount=0
foreach($line in Get-Content -LiteralPath $leader){if($line-notmatch'^(Inp[^=]+)=(.*)$'){continue};$name=$Matches[1];if(!$base.Contains($name)){throw "Leader input missing: $name"};$base[$name]=$line;$leaderCount++};if($leaderCount-ne185){throw "Expected 185 leader inputs, found $leaderCount."}
Set-FixedInput $base 'InpEvidenceSourceHash' $sourceHash -StringValue;Set-FixedInput $base 'InpEvidenceRunLabel' 'four_lane_m15_squeeze_target_interaction_discovery_model1' -StringValue;Set-FixedInput $base 'InpLogTrades' 'false';Set-FixedInput $base 'InpShowDashboard' 'false'
$variants=@(
   [pscustomobject]@{Name='sqt_exact_control';Role='exact_leader_control';Enabled='false';Positions='3';Target='1.50'},
   [pscustomobject]@{Name='sqt_capacity_control';Role='disabled_four_position_control';Enabled='false';Positions='4';Target='1.50'},
   [pscustomobject]@{Name='sqt_reference150';Role='enabled_reference';Enabled='true';Positions='4';Target='1.50'},
   [pscustomobject]@{Name='sqt_low175';Role='lower_neighbor';Enabled='true';Positions='4';Target='1.75'},
   [pscustomobject]@{Name='sqt_center200';Role='fixed_center';Enabled='true';Positions='4';Target='2.00'},
   [pscustomobject]@{Name='sqt_high225';Role='upper_neighbor';Enabled='true';Positions='4';Target='2.25'}
)
$windows=@([pscustomobject]@{Name='older_2015_2018';From='2015.01.01';To='2018.12.31'},[pscustomobject]@{Name='discovery_2019_2020';From='2019.01.01';To='2020.12.31'},[pscustomobject]@{Name='continuous_2015_2020';From='2015.01.01';To='2020.12.31'})
$stopRule='Discovery only. Both disabled controls and the enabled 1.50R reference must exactly reproduce their prior identities. Fixed 2.00R center must be profitable and no worse than leader control in each disjoint era, improve continuous net >=10% and CAGR >=0.20 point, retain PF >=98% of control, recovery and return/drawdown >=control, keep DD <=1.30% and <=control+0.15 point, and retain >=300 trades. At least one 1.75R or 2.25R neighbor must be no worse than control in both eras, improve net >=8% and CAGR >=0.15 point, retain PF/recovery/return-DD >=98% of control, meet the same DD and activity limits, and differ from the 1.50R reference. No alternate target selection or threshold rescue after observation.'
$package=Resolve-RepoPath $PackageDir;Clear-OutputDirSafe $package;$configDir=Join-Path $package 'configs';$profileDir=Join-Path $package 'profiles';$reportDir=Join-Path $package 'reports_here';$sourceDir=Join-Path $package 'source';New-Item -ItemType Directory -Path $configDir,$profileDir,$reportDir,$sourceDir -Force|Out-Null;Copy-Item $source (Join-Path $sourceDir 'Professional_XAUUSD_EA.mq5') -Force
$rows=[Collections.Generic.List[object]]::new();$ordinal=0;$candidateRank=0
foreach($variant in $variants){$candidateRank++;$inputs=Copy-Inputs $base;Set-FixedInput $inputs 'InpSQEnabled' $variant.Enabled;Set-FixedInput $inputs 'InpSQRiskPercent' '0.10';Set-FixedInput $inputs 'InpSQTakeProfitR' $variant.Target;Set-FixedInput $inputs 'InpMaximumAccountPositions' $variant.Positions;$profilePath=Join-Path $profileDir "$($variant.Name).set";@($inputs.Keys|Sort-Object|ForEach-Object{$inputs[$_]})|Set-Content $profilePath -Encoding ASCII;$profileHash=(Get-FileHash $profilePath -Algorithm SHA256).Hash.ToUpperInvariant();foreach($window in $windows){$ordinal++;$configName='{0:000}_{1}_{2}_m1.ini'-f$ordinal,$variant.Name,$window.Name;$configPath=Join-Path $configDir $configName;$reportName="$($variant.Name)_$($window.Name)_m1";Write-SeasonalTesterConfig -Path $configPath -ReportRoot $reportDir -ReportName $reportName -From $window.From -To $window.To -Inputs $inputs -Model 1 -Deposit 10000 -Period 15;$rows.Add([pscustomobject][ordered]@{QueueRank=$ordinal;Candidate=$variant.Name;CandidateRank=$candidateRank;Role=$variant.Role;Phase='four_lane_m15_squeeze_target_interaction_discovery_model1';Window=$window.Name;From=$window.From;To=$window.To;Model=1;Deposit=10000;FeatureEnabled=$variant.Enabled;MaximumAccountPositions=$variant.Positions;SqueezeRiskPercent='0.10';SqueezeTakeProfitR=$variant.Target;BreakoutLookbackBars='8';MaximumHoldBars='32';MaximumPortfolioOpenRiskPercent='0.75';ExpectedReportName=$reportName;PackageConfig="$PackageDir\configs\$configName";ReportDestination="$PackageDir\reports_here\$reportName";ConfigSha256=(Get-FileHash $configPath -Algorithm SHA256).Hash.ToUpperInvariant();ProfileSha256=$profileHash;SourceSha256=$sourceHash;StopRule=$stopRule})|Out-Null}}
$manifest=Resolve-RepoPath $ManifestPath;$rows|Export-Csv $manifest -NoTypeInformation -Encoding ASCII;$manifestHash=(Get-FileHash $manifest -Algorithm SHA256).Hash.ToUpperInvariant()
@('# Four-Lane M15 Squeeze Target Interaction Contract','','**Status: PREREGISTERED PRE-2021 SETTINGS INTERACTION. THE PUBLISHED LEADER AND FORWARD CANDIDATE ARE UNCHANGED.**','',"- Research source SHA-256: ``$sourceHash``","- Exact leader profile SHA-256: ``$leaderHash``","- Prior integration decision SHA-256: ``$expectedIntegrationDecisionHash``","- Exact integrated trade ledger SHA-256: ``$expectedLedgerHash``","- Independent squeeze decision SHA-256: ``$expectedIndependentDecisionHash``","- Manifest SHA-256: ``$manifestHash``",'','- The prior integrated 1.50R lane added 88 pre-2021 trades, +$209.91, PF 1.4954, and positive net in both eras, but portfolio PF retained only 94.68% of control. Separately, the original one-factor standalone matrix found 2.00R improved net and PF over its 1.50R center. Their eight-bar plus 2.00R interaction has not been tested before this freeze.','- Entry, squeeze, trend, stop, break-even, session, risk, lot, account-cap, loss-limit, capital-contract, and real-account settings are unchanged. Only the fixed squeeze target is bracketed.',"- $stopRule",'- Reject any identity mismatch, control/reference mismatch, losing era, efficiency failure, isolated center, or result needing a new target after observation. Only the exact 2.00R center may open a separately frozen post-2020 gate.','- No martingale, grid, averaging down, recovery sizing, capital change, forward substitution, or real-account trading.')|Set-Content (Resolve-RepoPath $ContractPath) -Encoding ASCII
[pscustomobject]@{Status='READY';SourceSha256=$sourceHash;ManifestSha256=$manifestHash;Variants=$variants.Count;Windows=$windows.Count;Configurations=$ordinal;Inputs=$base.Count;PackageDir=$PackageDir}
