param(
   [string]$ResultsPath='outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_DISCOVERY_MODEL1_RESULTS.csv',
   [string]$ManifestPath='outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_DISCOVERY_MODEL1_MANIFEST.csv',
   [string]$RunPath='outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_DISCOVERY_RUN_ATTESTATION.csv',
   [string]$CompilePath='outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_COMPILE_AUDIT.csv',
   [string]$DecisionCsvPath='outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_DISCOVERY_DECISION.csv',
   [string]$DecisionMarkdownPath='outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_DISCOVERY_DECISION.md'
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$expectedSource='B6810B305549968E2273DAAF736A63759FE5C16F3B416F5C69E39840FBE5173E';$expectedBinary='F7B36799594D40E335F0D5B560BA283102B501C72BCF20E1998E3F0F586FD13A'
function Resolve-RepoPath([string]$Path){if([IO.Path]::IsPathRooted($Path)){return $Path};return Join-Path $repo $Path};function Money([double]$v){if($v-ge0){return ('+${0:N2}'-f$v)};return ('-${0:N2}'-f[math]::Abs($v))}
$results=@(Import-Csv (Resolve-RepoPath $ResultsPath));$manifest=@(Import-Csv (Resolve-RepoPath $ManifestPath));$runs=@(Import-Csv (Resolve-RepoPath $RunPath));$compile=@(Import-Csv (Resolve-RepoPath $CompilePath))
if($results.Count-ne15-or$manifest.Count-ne15-or$runs.Count-ne15){throw 'Expected 15 results, manifest rows, and runs.'};if(@($results|Where-Object Status -ne PARSED).Count-or@($runs|Where-Object Status -ne REPORT_FOUND).Count){throw 'Evidence incomplete.'};if(@($results|Where-Object{$_.To-gt'2020.12.31'}).Count){throw 'Post-2020 leak.'}
if($compile.Count-ne1-or$compile[0].Status-ne'COMPILE_PASS'-or$compile[0].SourceSha256-ne$expectedSource-or$compile[0].PortableBinarySha256-ne$expectedBinary-or[int]$compile[0].CompileErrors-ne0-or[int]$compile[0].CompileWarnings-ne0){throw 'Compile identity mismatch.'}
foreach($row in $results){$m=@($manifest|Where-Object QueueRank -eq $row.QueueRank);$run=@($runs|Where-Object QueueRank -eq $row.QueueRank);if($m.Count-ne1-or$run.Count-ne1-or$row.ProfileSha256-ne$m[0].ProfileSha256-or$row.SourceSha256-ne$expectedSource-or$run[0].PackageSourceSha256-ne$expectedSource-or$run[0].PortableBinarySha256-ne$expectedBinary){throw "Identity mismatch at rank $($row.QueueRank)."}}
$base=@();foreach($group in ($results|Group-Object Candidate)){$o=@($group.Group|Where-Object Window -eq older_2015_2018);$r=@($group.Group|Where-Object Window -eq discovery_2019_2020);$c=@($group.Group|Where-Object Window -eq continuous_2015_2020);if($group.Count-ne3-or$o.Count-ne1-or$r.Count-ne1-or$c.Count-ne1){throw "Window mismatch for $($group.Name)."};$x=$c[0];$base+=[pscustomobject]@{Candidate=$group.Name;Role=$x.Role;Stop=[int]$x.StopLookbackBars;Older=[double]$o[0].NetProfit;Recent=[double]$r[0].NetProfit;Net=[double]$x.NetProfit;Cagr=[double]$x.CagrPercent;PF=[double]$x.ProfitFactor;Trades=[int]$x.TotalTrades;DD=[double]$x.MaxDrawdownPercent;Recovery=[double]$x.RecoveryFactor;ReturnDD=if([double]$x.MaxDrawdownPercent-gt0){[double]$x.TotalReturnPercent/[double]$x.MaxDrawdownPercent}else{0}}}
$control=@($base|Where-Object Candidate -eq rvsg_control5);if($control.Count-ne1){throw 'Control missing.'};$control=$control[0]
$rows=foreach($row in $base){$olderRet=$row.Older/$control.Older;$recentRet=$row.Recent/$control.Recent;$netGrowth=$row.Net/$control.Net-1;$cagrGrowth=$row.Cagr-$control.Cagr;$positive=$row.Older-gt0-and$row.Recent-gt0;$retain=$olderRet-ge.98-and$recentRet-ge.98;$tradeRet=$row.Trades-ge[math]::Ceiling(.98*$control.Trades);$eff=$row.PF-ge$control.PF-and$row.Recovery-ge$control.Recovery-and$row.ReturnDD-ge$control.ReturnDD;$dd=$row.DD-le1.25-and$row.DD-le$control.DD+.10;$growth=if($row.Candidate-eq'rvsg_center3'){$netGrowth-ge.05-and$cagrGrowth-ge.10}elseif($row.Candidate-in@('rvsg_stop2','rvsg_stop4')){$netGrowth-ge.03-and$cagrGrowth-ge.05}else{$false};$gate=$row.Candidate-ne'rvsg_control5'-and$positive-and$retain-and$tradeRet-and$eff-and$dd-and$growth;[pscustomobject]@{Candidate=$row.Candidate;Role=$row.Role;StopLookbackBars=$row.Stop;OlderNet=[math]::Round($row.Older,2);OlderRetentionPercent=[math]::Round(100*$olderRet,2);RecentNet=[math]::Round($row.Recent,2);RecentRetentionPercent=[math]::Round(100*$recentRet,2);ContinuousNet=[math]::Round($row.Net,2);NetGrowthPercent=[math]::Round(100*$netGrowth,2);CagrPercent=[math]::Round($row.Cagr,2);CagrGrowthPoints=[math]::Round($cagrGrowth,2);ProfitFactor=[math]::Round($row.PF,2);Trades=$row.Trades;MaxDrawdownPercent=[math]::Round($row.DD,2);RecoveryFactor=[math]::Round($row.Recovery,4);ReturnDrawdownRatio=[math]::Round($row.ReturnDD,4);PositiveEras=$positive;RetainsBothEras=$retain;TradeRetentionPass=$tradeRet;EfficiencyNoWorse=$eff;DrawdownPass=$dd;GrowthPass=$growth;DiscoveryGatePass=$gate}}
$center=@($rows|Where-Object Candidate -eq rvsg_center3);$support=@($rows|Where-Object{$_.Candidate-in@('rvsg_stop2','rvsg_stop4')-and$_.DiscoveryGatePass}).Count;$open=$center.Count-eq1-and$center[0].DiscoveryGatePass-and$support-ge1
$decisionRows=$rows|Sort-Object StopLookbackBars|ForEach-Object{$_|Add-Member -NotePropertyName Decision -NotePropertyValue $(if($open-and$_.DiscoveryGatePass){'OPEN_FROZEN_HOLDOUT'}else{'REJECTED_NO_HOLDOUT_NO_MODEL4'}) -PassThru};$decisionRows|Export-Csv (Resolve-RepoPath $DecisionCsvPath) -NoTypeInformation -Encoding ASCII
$md=[Collections.Generic.List[string]]::new();$md.Add('# Reversion Stop-Geometry Discovery Decision');$md.Add('');$md.Add($(if($open){'**Decision: discovery passed. Open only the frozen center and adjacent support in post-2020 Model 1 holdout.**'}else{'**Decision: rejected in frozen pre-2021 discovery. No holdout, Model 4, promotion, forward change, or live approval was opened.**'}));$md.Add('');$md.Add("- Exact leader source SHA-256: ``$expectedSource``");$md.Add("- Exact four-worker EX5 SHA-256: ``$expectedBinary``");$md.Add('- Reports: `15 / 15` parsed and identity-valid after one unchanged export recovery.');$md.Add('- Data: 2015-2020 Model 1 only.');$md.Add('');$md.Add('| Candidate | Stop bars | 2015-18 | 2019-20 | Continuous | Change | CAGR | PF | Trades | DD | Recovery | Gate |');$md.Add('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|');foreach($row in $decisionRows){$md.Add("| ``$($row.Candidate)`` | ``$($row.StopLookbackBars)`` | ``$(Money $row.OlderNet)`` | ``$(Money $row.RecentNet)`` | ``$(Money $row.ContinuousNet)`` | ``$('{0:N2}'-f$row.NetGrowthPercent)%`` | ``$('{0:N2}'-f$row.CagrPercent)%`` | ``$('{0:N2}'-f$row.ProfitFactor)`` | ``$($row.Trades)`` | ``$('{0:N2}'-f$row.MaxDrawdownPercent)%`` | ``$('{0:N2}'-f$row.RecoveryFactor)`` | ``$(if($row.DiscoveryGatePass){'pass'}else{'fail'})`` |")};$md.Add('');$md.Add($(if($open){"The frozen 3-bar center passed with $support adjacent support row(s). Newer data remains sealed until a dedicated holdout package freezes these exact profiles."}else{'The fixed center did not achieve the required broad-era growth and no-worse efficiency with adjacent support. The stop threshold is not moved after observation.'}));$md.Add('');$md.Add('- The historical leader and invalid forward registration remain unchanged.');$md|Set-Content (Resolve-RepoPath $DecisionMarkdownPath) -Encoding ASCII
[pscustomobject]@{Status=if($open){'OPEN_FROZEN_HOLDOUT'}else{'REJECTED'};Reports=15;Candidates=5;CenterPass=$center[0].DiscoveryGatePass;AdjacentPasses=$support;HoldoutOpened=$open;Model4Runs=0;NewBest=$false}
