[CmdletBinding()]
param([ValidateRange(1,100)][int]$MaxCpuPercent=80,[ValidateRange(1,1440)][int]$TimeoutMinutesPerConfig=8,[switch]$UserAuthorizedFocusRisk,[string]$ManifestPath='outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_MODEL1_MANIFEST.csv',[string]$OutputPrefix='FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_WORKER')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(!$UserAuthorizedFocusRisk){throw 'Controlled squeeze-target discovery requires explicit focus/window-risk authorization.'}
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$sharedWork=Split-Path -Parent $repo;$repoLock=Join-Path $PSScriptRoot 'MT5_LOCAL_LAUNCH_DISABLED.lock';$outerLock=Join-Path $sharedWork 'MT5_LOCAL_LAUNCH_DISABLED.lock';$unlockFile=Join-Path $PSScriptRoot 'ALLOW_MT5_LOCAL_LAUNCH.unlock';$focusAck=Join-Path $PSScriptRoot 'ALLOW_MT5_HIDDEN_DESKTOP_ACK.unlock';$runner=Join-Path $PSScriptRoot 'run_mt5_portable_parallel_manifest.ps1'
$candidate=if([IO.Path]::IsPathRooted($ManifestPath)){$ManifestPath}else{Join-Path $repo $ManifestPath};$manifest=(Resolve-Path -LiteralPath $candidate).Path;$main=(Resolve-Path -LiteralPath (Join-Path $repo 'outputs\FOUR_LANE_M15_SQUEEZE_TARGET_INTERACTION_DISCOVERY_MODEL1_MANIFEST.csv')).Path
$source=Join-Path $repo 'outputs\four_lane_m15_squeeze_target_interaction_discovery_model1_package\source\Professional_XAUUSD_EA.mq5';$expectedManifestHash='770B30C810054928F02E04ECE6FA8ADA3279D71D7DBD32C57F3B9608CC33695E';$expectedSourceHash='5D756F58DDAB31D2DC909B8DD800C8D888582691A7208FFD7FD1E3F597D3A5C6';$expectedBinaryHash='9BC3BAEC7D5BA0945E6974C960AC900D6F019C5A174D217712FF8B7E8137C32A'
$roots=@((Join-Path $sharedWork 'mt5_portable_research'),(Join-Path $sharedWork 'mt5_portable_research_w2'),(Join-Path $sharedWork 'mt5_portable_research_w3'),(Join-Path $sharedWork 'mt5_portable_research_w4'))
if($manifest.Equals($main,[StringComparison]::OrdinalIgnoreCase)){if((Get-FileHash $manifest -Algorithm SHA256).Hash.ToUpperInvariant()-ne$expectedManifestHash){throw 'Main manifest identity changed.'}}
else{$roots=@($roots[0]);$rows=@(Import-Csv $manifest);$mainRows=@(Import-Csv $main);if($rows.Count-lt1){throw 'Recovery manifest is empty.'};foreach($row in $rows){$match=@($mainRows|Where-Object QueueRank -eq $row.QueueRank);if($match.Count-ne1-or$row.ConfigSha256-ne$match[0].ConfigSha256-or$row.SourceSha256-ne$expectedSourceHash){throw "Recovery changed rank $($row.QueueRank)."}}}
foreach($required in @($repoLock,$outerLock,$runner,$manifest,$source)+$roots){if(!(Test-Path -LiteralPath $required)){throw "Discovery prerequisite missing: $required"}}
if((Get-FileHash $source -Algorithm SHA256).Hash.ToUpperInvariant()-ne$expectedSourceHash){throw 'Package source identity changed.'};foreach($root in $roots){$installedSource=Join-Path $root 'MQL5\Experts\Professional_XAUUSD_EA.mq5';$binary=Join-Path $root 'MQL5\Experts\Professional_XAUUSD_EA.ex5';$identity=@(Get-Content -LiteralPath (Join-Path $root 'MQL5\Experts\Professional_XAUUSD_EA.compiled_identity.txt'));if((Get-FileHash $installedSource -Algorithm SHA256).Hash.ToUpperInvariant()-ne$expectedSourceHash-or(Get-FileHash $binary -Algorithm SHA256).Hash.ToUpperInvariant()-ne$expectedBinaryHash-or$identity.Count-lt2-or$identity[0]-ne$expectedSourceHash-or$identity[1]-ne$expectedBinaryHash){throw "Portable source/binary identity mismatch: $root"}}
if((Test-Path $unlockFile)-or(Test-Path $focusAck)-or$env:ALLOW_MT5_FOCUS_RISK-eq'1'-or$env:ALLOW_MT5_HIDDEN_DESKTOP_ACK-eq'1'){throw 'Discovery refuses a pre-existing partial unlock state.'};if(@(Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue).Count-ne0){throw 'Discovery requires zero pre-existing MT5 processes.'}
$repoLockBytes=[IO.File]::ReadAllBytes($repoLock);$outerLockBytes=[IO.File]::ReadAllBytes($outerLock);$started=[DateTime]::UtcNow.ToString('o');$complete=$false
try{[IO.File]::Delete($repoLock);[IO.File]::Delete($outerLock);[IO.File]::WriteAllText($unlockFile,"Squeeze-target discovery $started",[Text.Encoding]::ASCII);[IO.File]::WriteAllText($focusAck,"Squeeze-target focus acknowledgement $started",[Text.Encoding]::ASCII);$env:ALLOW_MT5_FOCUS_RISK='1';$env:ALLOW_MT5_HIDDEN_DESKTOP_ACK='1';&$runner -ManifestPath $manifest -PortableRoots $roots -UserAuthorizedFocusRisk -OutputPrefix $OutputPrefix -MaxCpuPercent $MaxCpuPercent -TimeoutMinutesPerConfig $TimeoutMinutesPerConfig -ExpectedPortableBinarySha256 $expectedBinaryHash -ProgressIntervalSeconds 10;$complete=$true}
finally{Remove-Item $unlockFile,$focusAck -Force -ErrorAction SilentlyContinue;Remove-Item Env:ALLOW_MT5_FOCUS_RISK -ErrorAction SilentlyContinue;Remove-Item Env:ALLOW_MT5_HIDDEN_DESKTOP_ACK -ErrorAction SilentlyContinue;[IO.File]::WriteAllBytes($repoLock,$repoLockBytes);[IO.File]::WriteAllBytes($outerLock,$outerLockBytes);Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue}
if(!$complete){throw 'Controlled squeeze-target discovery did not complete.'};if(!(Test-Path $repoLock)-or!(Test-Path $outerLock)-or@(Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue).Count-ne0){throw 'Discovery did not restore hard-lock state.'}
[pscustomobject]@{Status='CONTROLLED_DISCOVERY_COMPLETE';StartedAtUtc=$started;CompletedAtUtc=[DateTime]::UtcNow.ToString('o');Configurations=@(Import-Csv $manifest).Count;Workers=$roots.Count;MaxCpuPercent=$MaxCpuPercent;LaunchLocksRestored=$true;MT5Processes=0;ForwardCandidateChanged=$false;RealAccountApproved=$false}
