[CmdletBinding()]
param([ValidateRange(1,100)][int]$MaxCpuPercent=80,[switch]$UserAuthorizedFocusRisk)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(!$UserAuthorizedFocusRisk){throw 'Controlled stop-geometry compile requires explicit focus/window-risk authorization.'}
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$sharedWork=Split-Path -Parent $repo
$source=Join-Path $repo 'outputs\three_lane_reversion_stop_geometry_discovery_model1_package\source\Professional_XAUUSD_EA.mq5';$expectedSourceHash='B6810B305549968E2273DAAF736A63759FE5C16F3B416F5C69E39840FBE5173E'
$preparer=Join-Path $PSScriptRoot 'prepare_mt5_portable_shared_expert.ps1';$repoLock=Join-Path $PSScriptRoot 'MT5_LOCAL_LAUNCH_DISABLED.lock';$outerLock=Join-Path $sharedWork 'MT5_LOCAL_LAUNCH_DISABLED.lock';$unlockFile=Join-Path $PSScriptRoot 'ALLOW_MT5_LOCAL_LAUNCH.unlock';$focusAck=Join-Path $PSScriptRoot 'ALLOW_MT5_HIDDEN_DESKTOP_ACK.unlock';$auditPath=Join-Path $repo 'outputs\THREE_LANE_REVERSION_STOP_GEOMETRY_COMPILE_AUDIT.csv'
$roots=@((Join-Path $sharedWork 'mt5_portable_research'),(Join-Path $sharedWork 'mt5_portable_research_w2'),(Join-Path $sharedWork 'mt5_portable_research_w3'),(Join-Path $sharedWork 'mt5_portable_research_w4'))
foreach($required in @($source,$preparer,$repoLock,$outerLock)){if(!(Test-Path -LiteralPath $required -PathType Leaf)){throw "Compile prerequisite missing: $required"}}
if((Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToUpperInvariant() -ne $expectedSourceHash){throw 'Stop-geometry source identity changed.'}
if((Test-Path -LiteralPath $unlockFile) -or (Test-Path -LiteralPath $focusAck) -or $env:ALLOW_MT5_FOCUS_RISK -eq '1' -or $env:ALLOW_MT5_HIDDEN_DESKTOP_ACK -eq '1'){throw 'Compile refuses a pre-existing partial unlock state.'};if(@(Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue).Count -ne 0){throw 'Compile requires zero MT5-family processes.'}
$repoLockBytes=[IO.File]::ReadAllBytes($repoLock);$outerLockBytes=[IO.File]::ReadAllBytes($outerLock);$started=[DateTime]::UtcNow.ToString('o');$compileResult=$null
try{[IO.File]::Delete($repoLock);[IO.File]::Delete($outerLock);[IO.File]::WriteAllText($unlockFile,"Stop-geometry compile $started",[Text.Encoding]::ASCII);[IO.File]::WriteAllText($focusAck,"Stop-geometry focus acknowledgement $started",[Text.Encoding]::ASCII);$env:ALLOW_MT5_FOCUS_RISK='1';$env:ALLOW_MT5_HIDDEN_DESKTOP_ACK='1';$output=@(& $preparer -SourcePath $source -ExpectedSourceSha256 $expectedSourceHash -PortableRoots $roots -MaxCpuPercent $MaxCpuPercent -CompileTimeoutMinutes 5 -UserAuthorizedFocusRisk);$candidate=@($output|Where-Object{$_.PSObject.Properties.Name -contains 'PortableBinarySha256'});if($candidate.Count){$compileResult=$candidate[-1]}}
finally{Remove-Item -LiteralPath $unlockFile,$focusAck -Force -ErrorAction SilentlyContinue;Remove-Item Env:ALLOW_MT5_FOCUS_RISK -ErrorAction SilentlyContinue;Remove-Item Env:ALLOW_MT5_HIDDEN_DESKTOP_ACK -ErrorAction SilentlyContinue;[IO.File]::WriteAllBytes($repoLock,$repoLockBytes);[IO.File]::WriteAllBytes($outerLock,$outerLockBytes);Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue}
if($null -eq $compileResult -or [string]::IsNullOrWhiteSpace([string]$compileResult.PortableBinarySha256)){throw 'Compile did not produce a shared binary.'}
$binaryRows=@($roots|ForEach-Object{$src=Join-Path $_ 'MQL5\Experts\Professional_XAUUSD_EA.mq5';$bin=Join-Path $_ 'MQL5\Experts\Professional_XAUUSD_EA.ex5';$id=@(Get-Content -LiteralPath (Join-Path $_ 'MQL5\Experts\Professional_XAUUSD_EA.compiled_identity.txt'));$sh=(Get-FileHash -LiteralPath $src -Algorithm SHA256).Hash.ToUpperInvariant();$bh=(Get-FileHash -LiteralPath $bin -Algorithm SHA256).Hash.ToUpperInvariant();[pscustomobject]@{SourceSha256=$sh;BinarySha256=$bh;IdentityReady=$id.Count -ge 2 -and $id[0] -eq $sh -and $id[1] -eq $bh}})
$binaryHashes=@($binaryRows|Where-Object IdentityReady|Select-Object -ExpandProperty BinarySha256 -Unique);if($binaryRows.Count -ne 4 -or $binaryHashes.Count -ne 1){throw 'Binary identity is not exact across four workers.'}
if(!(Test-Path -LiteralPath $repoLock) -or !(Test-Path -LiteralPath $outerLock) -or @(Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue).Count -ne 0){throw 'Compile did not restore hard-lock state.'}
$audit=[pscustomobject][ordered]@{Status='COMPILE_PASS';StartedAtUtc=$started;CompletedAtUtc=[DateTime]::UtcNow.ToString('o');SourceSha256=$expectedSourceHash;PortableBinarySha256=$binaryHashes[0];Workers=4;CompileErrors=0;CompileWarnings=0;LaunchLocksRestored=$true;MT5Processes=0;ForwardCandidateChanged=$false;RealAccountApproved=$false};$audit|Export-Csv -LiteralPath $auditPath -NoTypeInformation -Encoding ASCII;$audit
