[CmdletBinding()]
param([ValidateRange(1,100)][int]$MaxCpuPercent=80,[ValidateRange(1,1440)][int]$TimeoutMinutesPerConfig=15,[switch]$UserAuthorizedFocusRisk)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if(!$UserAuthorizedFocusRisk){throw 'Controlled squeeze telemetry run requires explicit focus/window-risk authorization.'}
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$sharedWork=Split-Path -Parent $repo
$manifest=Join-Path $repo 'outputs\FOUR_LANE_M15_SQUEEZE_FEATURE_TELEMETRY_MODEL1_MANIFEST.csv';$source=Join-Path $repo 'outputs\four_lane_m15_squeeze_feature_telemetry_model1_package\source\Professional_XAUUSD_EA.mq5'
$expectedManifestHash='80FA027F757922A9E5404DCD682BC769F2328E5D8FC6F86CEED592B374BB1C07';$expectedSourceHash='C6B4BC66F661BB70CC51B92E320A87A5643745454C26791B09766F84DA9C94C4';$expectedBinaryHash='EAC3F26DDCE7E7FC59CD02AFFE3F358397FCABF4F9D402F8F0B6D27B8EE3AA9C'
$repoLock=Join-Path $PSScriptRoot 'MT5_LOCAL_LAUNCH_DISABLED.lock';$outerLock=Join-Path $sharedWork 'MT5_LOCAL_LAUNCH_DISABLED.lock';$unlockFile=Join-Path $PSScriptRoot 'ALLOW_MT5_LOCAL_LAUNCH.unlock';$focusAck=Join-Path $PSScriptRoot 'ALLOW_MT5_HIDDEN_DESKTOP_ACK.unlock';$runner=Join-Path $PSScriptRoot 'run_mt5_portable_parallel_manifest.ps1';$root=Join-Path $sharedWork 'mt5_portable_research'
$commonFiles=Join-Path $env:APPDATA 'MetaQuotes\Terminal\Common\Files';$eventName='SQUEEZE_FEATURE_TELEMETRY_2015_2020.csv';$eventSource=Join-Path $commonFiles $eventName;$eventDestination=Join-Path $repo 'outputs\FOUR_LANE_M15_SQUEEZE_FEATURE_TELEMETRY_EVENTS.csv'
$logNames=@($eventName,'SQUEEZE_FEATURE_TELEMETRY_RV_AUX.csv','SQUEEZE_FEATURE_TELEMETRY_MO_AUX.csv','SQUEEZE_FEATURE_TELEMETRY_ATB_AUX.csv')
foreach($required in @($manifest,$source,$repoLock,$outerLock,$runner,$root,$commonFiles)){if(!(Test-Path -LiteralPath $required)){throw "Telemetry prerequisite missing: $required"}}
if((Get-FileHash -LiteralPath $manifest -Algorithm SHA256).Hash.ToUpperInvariant() -ne $expectedManifestHash){throw 'Telemetry manifest identity changed.'};if((Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToUpperInvariant() -ne $expectedSourceHash){throw 'Telemetry package source identity changed.'}
$binary=Join-Path $root 'MQL5\Experts\Professional_XAUUSD_EA.ex5';if(!(Test-Path -LiteralPath $binary -PathType Leaf) -or (Get-FileHash -LiteralPath $binary -Algorithm SHA256).Hash.ToUpperInvariant() -ne $expectedBinaryHash){throw 'Portable binary identity mismatch.'}
foreach($name in $logNames){$path=Join-Path $commonFiles $name;if(Test-Path -LiteralPath $path){throw "Telemetry log must be absent before the frozen run: $path"}}
if(Test-Path -LiteralPath $eventDestination){throw 'Published telemetry destination must be absent before the frozen run.'}
if((Test-Path -LiteralPath $unlockFile) -or (Test-Path -LiteralPath $focusAck) -or $env:ALLOW_MT5_FOCUS_RISK -eq '1' -or $env:ALLOW_MT5_HIDDEN_DESKTOP_ACK -eq '1'){throw 'Telemetry run refuses a pre-existing partial unlock state.'};if(@(Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue).Count -ne 0){throw 'Telemetry run requires zero pre-existing MT5 processes.'}
$repoLockBytes=[IO.File]::ReadAllBytes($repoLock);$outerLockBytes=[IO.File]::ReadAllBytes($outerLock);$started=[DateTime]::UtcNow.ToString('o');$complete=$false
try{[IO.File]::Delete($repoLock);[IO.File]::Delete($outerLock);[IO.File]::WriteAllText($unlockFile,"Squeeze telemetry run $started",[Text.Encoding]::ASCII);[IO.File]::WriteAllText($focusAck,"Squeeze telemetry focus acknowledgement $started",[Text.Encoding]::ASCII);$env:ALLOW_MT5_FOCUS_RISK='1';$env:ALLOW_MT5_HIDDEN_DESKTOP_ACK='1';& $runner -ManifestPath $manifest -PortableRoots @($root) -UserAuthorizedFocusRisk -OutputPrefix 'FOUR_LANE_M15_SQUEEZE_FEATURE_TELEMETRY_WORKER' -MaxCpuPercent $MaxCpuPercent -TimeoutMinutesPerConfig $TimeoutMinutesPerConfig -ExpectedPortableBinarySha256 $expectedBinaryHash -ProgressIntervalSeconds 10;$complete=$true}
finally{Remove-Item -LiteralPath $unlockFile,$focusAck -Force -ErrorAction SilentlyContinue;Remove-Item Env:ALLOW_MT5_FOCUS_RISK -ErrorAction SilentlyContinue;Remove-Item Env:ALLOW_MT5_HIDDEN_DESKTOP_ACK -ErrorAction SilentlyContinue;[IO.File]::WriteAllBytes($repoLock,$repoLockBytes);[IO.File]::WriteAllBytes($outerLock,$outerLockBytes);Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue|Stop-Process -Force -ErrorAction SilentlyContinue;if(Test-Path -LiteralPath $eventSource -PathType Leaf){Copy-Item -LiteralPath $eventSource -Destination $eventDestination -Force}}
if(!$complete){throw 'Controlled squeeze telemetry run did not complete.'};if(!(Test-Path -LiteralPath $eventDestination -PathType Leaf)){throw 'Telemetry event log was not recovered.'};if(!(Test-Path -LiteralPath $repoLock) -or !(Test-Path -LiteralPath $outerLock) -or @(Get-Process -Name terminal,terminal64,metatester,metatester64,MetaEditor,metaeditor64 -ErrorAction SilentlyContinue).Count -ne 0){throw 'Telemetry run did not restore hard-lock state.'}
[pscustomobject][ordered]@{Status='CONTROLLED_TELEMETRY_COMPLETE';StartedAtUtc=$started;CompletedAtUtc=[DateTime]::UtcNow.ToString('o');Configurations=1;Workers=1;MaxCpuPercent=$MaxCpuPercent;EventSha256=(Get-FileHash -LiteralPath $eventDestination -Algorithm SHA256).Hash.ToUpperInvariant();LaunchLocksRestored=$true;MT5Processes=0;ForwardCandidateChanged=$false;RealAccountApproved=$false}
